---
- name: Install http service
  hosts: all
 # become: true
#remote_user: ansible

  tasks:
    - name: create a group
      group:
        name: apache
        state: present

    - name: create a user
      user:
        name: apache
        state: present
        group: apache

    - name: Install httpd sevice
      yum:
        name: httpd
        state: latest
 
   # - name: httpd.conf configuration file
   #   get_url:
   #     url: http://myblogmchopker.blogspot.com/2017/08/ansible-tomcat-installation-deployment.html
   #     dest: /etc/httpd/conf/httpd.conf
   #     force: yes
   #     owner: apache
   #     group: apache
    - name: chnage index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "hello from {{ ansible_hostname }}"
        create: yes
    - name: start httpd service
      service:
        name: httpd
        state: started
        enabled: true
    - name: set timezone
      shell: timedatectl set-timezone Australia/Sydney

    - name: Install NTP
      yum: name=ntp state=installed
      tags: ntp

    - name: Copy over the NTP configuration
      lineinfile:
        path: /etc/ntp.conf
        line: 'server 10.0.4.223 iburst'
      notify:
      - restart ntpd
      tags: ntp

    - name: Make sure NTP is stopped
      service: name=ntpd state=stopped enabled=yes
      tags: ntp

    - name: Sync time initialy
      shell: ntpdate -q 10.0.4.223
      tags: ntp

    - name: Make sure NTP is started up
      service: name=ntpd state=running enabled=yes
      tags: ntp

    - name: Sync hwclock
      shell: hwclock -w
      tags: ntp

 #   handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted
    - name: Install firewalld service
      yum:
        name: firewalld
        state: present
    - name: start firewalld
      shell: name=firewalld state=started enabled=yes
